FROM {{ image_spec("designate-base") }}
MAINTAINER {{ maintainer }}

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
       --no-install-suggests \
       bind9

RUN mkdir -p /var/run/named /etc/bind \
    && chmod 775 /var/run/named \
    && chown root:bind /var/run/named

RUN apt-get clean
