FROM {{ image_spec("designate-base") }}
MAINTAINER {{ maintainer }}

#mysql-client only for provisioning need to be removed later
RUN apt-get install -y --no-install-recommends \
        mysql-client \
    && apt-get clean

USER designate
