configs:
  designate:
    api_port:
      cont: 9001
      ingress: dns
    mdns_port:
      cont: 5354
    rndc_port:
      cont: 953
    bind_port:
      cont: 53
    worker_port:
      cont: 5358
    debug: true
    notification:
      driver: noop
      topics:
        enabled: false
        names: changeme
    backend: bind9
    # options, allows to configure services particularly
    service:
      central:
        workers: 1
        threads: 1000
      api:
        workers: 1
        threads: 1000
      mdns:
        workers: 1
        threads: 1000
      agent:
        workers: 1
      zone_manager:
        workers: 1
        threads: 1000
      pool_manager:
        workers: 1
        threads: 1000
    domain_purge:
      interval: 3600
      batch_size: 100
      time_threshold: 604800  # 7 days

secret_configs:
  designate:
    username: designate
    password: password
    db:
      username: designate
      password: password
      name:
        pool_manager: designate_pool_manager
        main_database: designate

secret_configs:
  designate:
    rndc_key_secret: fapwtRlIgYwYeQeyY3U1+Q==

sources:
  openstack/designate:
    git_url: https://git.openstack.org/openstack/designate.git
    git_ref: stable/newton
